const CRONOGRAMA = [
  {
    left: 150,  w: 100, h: 220,
    year: '388 a.C.',
    es:   'Primeras trampas del deporte',
    body: 'Eufolio, boxeador, pagó a tres oponentes para que se dejaran caer y asegurar así su victoria en los juegos del 388 a.C.',
    img:  'fotos/42.jpg',
  },
  {
    left: 340,  w: 160, h: 80,
    year: '1540',
    es:   'Vallvidrera Curling Club',
    body: 'Un año antes de que el curling naciera en Escocia, un club se adelantaba en Collserola. Jamás han jugado un partido: el pantano nunca se hiela lo suficiente.',
    img:  'fotos/61.jpeg',
  },
  {
    left: 560,  w: 55,  h: 300,
    year: '1884',
    es:   'Katie Sandwina',
    body: 'Artista de circo y sufragista. Considerada hasta 1986 «la mujer más fuerte del mundo».',
    img:  'fotos/43.webp',
  },
  {
    left: 680,  w: 180, h: 55,
    year: '1903',
    es:   'El farolillo rojo',
    body: 'Premio al último del Tour. Tuvo muchos adeptes que luchaban por ser les más lentes.',
    img:  'fotos/49.webp',
  },
  {
    left: 940,  w: 130, h: 120,
    year: '1904',
    es:   'Fred Lorz gana la maratón en coche',
    body: 'Tras correr 14 km, subió al coche de su entrenador. Se bajó poco antes de la meta y entró como ganador.',
    img:  'fotos/22.png',
  },
  {
    left: 1140, w: 65,  h: 340,
    year: '1935',
    es:   'Primera competición de Roller Derby',
    body: 'El 13 de agosto de 1935, en el Chicago Coliseum. Carrera de resistencia de larga distancia con equipos mixtos.',
    img:  'fotos/55.webp',
  },
  {
    left: 1270, w: 220, h: 60,
    year: '1936',
    es:   'Jesse Owens · Olimpiades Populars',
    body: 'Jesse Owens ganó cuatro oros en Berlín. Las Olimpiades Populars de Barcelona no llegaron a inaugurarse: el golpe de Estado lo impidió el día antes.',
    img:  'fotos/46.jpg',
  },
  {
    left: 1560, w: 90,  h: 180,
    year: '1960',
    es:   'Creación de los paralímpicos',
    body: 'El Dr. Guttmann organizó los primeros Juegos de Stoke Mandeville en 1948. Los primeros paralímpicos: Roma 1960.',
    img:  'fotos/27.jpg',
  },
  {
    left: 1730, w: 310, h: 90,
    year: '1968',
    es:   'Las Gardenias de Tepito',
    body: 'Equipo de fútbol de travestis y transexuales que lleva 50 años jugando maquilladas y con lentejuelas en El Maracaná de Tepito.',
    img:  'fotos/50.jpg',
  },
  {
    left: 1790, w: 55,  h: 200, wb: 90,
    year: '1969',
    es:   'Stop the Seventy Tour',
    body: 'Sabotajes creativos a la gira de los Springboks en pleno Apartheid: zanjas nocturnas, miles de chinchetas, encadenamientos.',
    img:  'fotos/52.jpg',
  },
  {
    left: 2120, w: 110, h: 140,
    year: '1973',
    es:   'Grupo Passion — Deporte de Ideas',
    body: '«El dogma competitivo nos parece repugnante». Arte conceptual desde dentro del deporte.',
    img:  'fotos/16.jpg',
  },
  {
    left: 2300, w: 190, h: 50,
    year: '1974',
    es:   'Nace la lucha de dedos de los pies',
    body: 'Conocido como Toe Wrestling, este deporte fue inventado por unos ingleses en un bar.',
    img:  'fotos/8.jpg',
  },
  {
    left: 2560, w: 50,  h: 290,
    year: '1982',
    es:   'Creación de los Gay Games',
    body: 'Creados en San Francisco por Tom Waddell, decatleta olímpico, para promover la inclusión de la comunidad gay y lesbiana.',
    img:  'fotos/32.webp',
  },
  {
    left: 2690, w: 150, h: 100,
    year: '1984',
    es:   'Nado sincronizado individual',
    body: 'Deporte olímpico olvidado presente en tres olimpiadas: 1984, 1988 y 1992. Sincronizarse con une misme no siempre fue sencillo.',
    img:  'fotos/29.jpg',
  },
  {
    left: 2920, w: 230, h: 75,
    year: '1988',
    es:   'Florence Griffith · Ballet de esquí',
    body: 'Campaña de acoso a Flo-Jo. Batió el récord y le dijeron que el velocímetro estaba roto. El ballet de esquí compite por primera vez en Calgary 88.',
    img:  'fotos/60.jpeg',
  },
  {
    left: 3220, w: 80,  h: 240,
    year: '1992',
    es:   'Petra, inspirada en Lorenza Böttner',
    body: 'Mascota paralímpica Barcelona 92, diseñada por Mariscal. Inspirada en Lorenza Böttner: pintora, performer, activista trans y anticapacitista.',
    img:  'fotos/11.jpg',
  },
  {
    left: 3370, w: 160, h: 65,
    year: '2000',
    es:   'Eric Moussambani',
    body: 'Sidney 2000. Completó los 100m en 1:52.72, más del doble del tiempo ganador. Aprendió a nadar 8 meses antes en una piscina de hotel de 12 metros.',
    img:  'fotos/eric.jpeg',
  },
  {
    left: 3600, w: 100, h: 230,
    year: '2004',
    es:   'Nace Samarucs València',
    body: 'Primer club polideportivo LGTBIQ+ de la Comunitat Valenciana. De aquí nace Parkuir.',
    img:  '',
  },
  {
    left: 3780, w: 140, h: 105,
    year: '2005',
    es:   'Nace el Quadball',
    body: 'Antes Quidditch. En 2022 cambió su nombre para desvincularse de J.K. Rowling tras sus declaraciones tránsfobas.',
    img:  'fotos/54.jpg',
  },
  {
    left: 4000, w: 200, h: 70,
    year: '2009',
    es:   'Caster Semenya vs World Athletics',
    body: 'Activista y atleta intersex. Rechaza medicarse para competir. Ha llevado su caso hasta el Tribunal Europeo de Derechos Humanos.',
    img:  'fotos/59.jpg',
  },
  {
    left: 4270, w: 75,  h: 250,
    year: '2014',
    es:   'Space-out Competition',
    body: 'Competición que premia a quien no haga nada durante 90 minutos manteniendo el ritmo cardíaco estable. Fundada por Woopsyang en Corea del Sur.',
    img:  '',
  },
  {
    left: 4430, w: 160, h: 80,
    year: '2021',
    es:   'Simone Biles · salud mental',
    body: 'Se retira de Tokio por salud mental, abriendo el debate sobre la presión psicológica en el deporte de élite.',
    img:  'fotos/18.png',
  },
  {
    left: 4670, w: 110, h: 160,
    year: '2023',
    es:   'Activistas plantan cebollas en campos de golf',
    body: 'XR y otros grupos siembran hortalizas en diez campos de golf para denunciar el despilfarro de agua en plena sequía.',
    img:  '',
  },
  {
    left: 4870, w: 250, h: 55,
    year: '2024',
    es:   'Imane Khelif · Paris 2024',
    body: 'Boxeadora argelina, oro en París. Recibió una campaña de odio transfóbica siendo mujer cis. Entre los atacantes: Elon Musk y J.K. Rowling.',
    img:  'fotos/44.jpg',
  },
  {
    left: 5100, w: 150, h: 120,
    year: '2024',
    es:   'Gay Games Valencia',
    body: 'Evento LGTB+ cuya financiación incluye donaciones de General Electric, fabricante de componentes militares utilizados en conflictos activos.',
    img:  '',
  },
  {
    left: 5380, w: 130, h: 340,
    year: '2026',
    es:   'Primera Copa Mundial de Sperm Racing',
    body: 'La machosfera convierte la carrera de esperma en deporte mundial. Podría haber sido una broma irónica de Parkuir, pero ellos llegaron más lejos.',
    img:  '',
  },
];