const CRONOGRAMA = [
  {
    left: 150, w: 100, h: 220,
    year: '388 a.C.',
    es: 'Primeras trampas del deporte',
    body: 'Eufolio, boxeador, pagó a tres oponentes para que se dejaran caer y asegurar así su victoria en los juegos del 388 a.C.',
    img: './../fotos/1.jpg',
  },
  {
    left: 330, w: 160, h: 80,
    year: '1540',
    es: 'Vallvidrera Curling Club',
    body: 'Un año antes de que el curling naciera en Escocia, un club se adelantaba en Collserola. Cada año bajan al pantano con una piedra para ver si el hielo aguanta un partido. En su medio milenio de historia jamás se ha dado la ocasión.',
    img: './../fotos/2.jpeg',
  },
  {
    left: 570, w: 80, h: 160,
    year: '1814',
    es: 'Creación Gimnasia Sueca',
    body: 'Per Henrik Ling crea la disciplina que nos hizo sufrir más tarde y la divide en cuatro ramas: pedagógica, militar, médica y estética.',
    img: './../fotos/4.png',
  },
  {
    left: 730, w: 55, h: 300,
    year: '1884',
    es: 'Katie Sandwina',
    body: 'Artista de circo, atleta de fuerza y sufragista. Considerada hasta 1986 «la mujer más fuerte del mundo».',
    img: './../fotos/3.jpg',
  },
  {
    left: 865, w: 160, h: 55,
    year: '1894',
    es: 'Primer registro del premio Cuchara de Madera',
    body: 'La Cuchara de Madera es un premio simbólico en rugby para quien queda en último lugar. Nace en contraposición al dicho «nacido bajo cuchara de plata».',
    img: './../fotos/5.jpg',
  },
  {
    left: 1105, w: 180, h: 55,
    year: '1900',
    es: 'Corte de pelo de poodles en los Juegos de París',
    body: '128 competidores tuvieron 2 horas para esquilar la mayor cantidad posible de caniches. La medalla de oro fue para Avril Lafoule, quien esquiló 17 caniches frente a 6000 personas.',
    img: './../fotos/8.jpg',
  },
  {
    left: 1365, w: 130, h: 120,
    year: '1903',
    es: 'El farolillo rojo',
    body: 'Premio al último del Tour. Tuvo muchos adeptes que luchaban por ser les más lentes, hasta que la vuelta ciclista lo convirtió en símbolo de superación.',
    img: './../fotos/6.webp',
  },
  {
    left: 1575, w: 130, h: 120,
    year: '1904',
    es: 'Fred Lorz gana la maratón en coche',
    body: 'Tras correr 14 km, subió al coche de su entrenador. Se bajó poco antes de la meta y entró como ganador. Estuvo a punto de recibir la medalla de oro antes de admitir que era una broma.',
    img: './../fotos/7.png',
  },
  {
    left: 1785, w: 80, h: 80,
    year: '1912',
    es: 'El duelo con pistolas entra en los Juegos Olímpicos',
    body: 'Los Juegos Olímpicos de Estocolmo incluyen el duelo con pistolas como deporte.',
    img: './../fotos/9.jpg',
  },
  {
    left: 1945, w: 80, h: 80,
    year: '1912',
    es: 'El arte entra en los Juegos Olímpicos',
    body: 'Desde Estocolmo 1912 hasta Londres 1948, el arte fue disciplina deportiva olímpica. Jean Jacoby ganó oros en 1924 y 1928, convirtiéndose en el artista olímpico de mayor éxito.',
    img: './../fotos/10.jpg',
  },
  {
    left: 2105, w: 80, h: 120,
    year: '1920',
    es: 'Niels Bukh y la gimnasia nazi',
    body: 'Gimnasta danés y entrenador nacional, fue excluido del equipo olímpico en 1908 en parte por homosexual. Simpatizó con el nazismo pese a convivir abiertamente con parejas masculinas.',
    img: './../fotos/11.jpg',
  },
  {
    left: 2265, w: 80, h: 100,
    year: '1934',
    es: 'Ana María Martínez Sagi obligada a dimitir del FCB',
    body: 'Primera mujer en la junta directiva del FC Barcelona. Intentó crear el equipo femenino pero fue obligada a dimitir por presiones externas y amenazas.',
    img: './../fotos/12.jpg',
  },
  {
    left: 2425, w: 65, h: 340,
    year: '1935',
    es: 'Primera competición de Roller Derby',
    body: 'El 13 de agosto de 1935, en el Chicago Coliseum. Carrera de resistencia de larga distancia con equipos mixtos.',
    img: './../fotos/13.webp',
  },
  {
    left: 2570, w: 120, h: 60,
    year: '1936',
    es: 'Jesse Owens',
    body: 'Atleta afroamericano que ganó cuatro medallas de oro en Berlín 1936, convirtiéndose en símbolo antirracista mundial.',
    img: './../fotos/14.jpg',
  },
  {
    left: 2770, w: 220, h: 60,
    year: '1936',
    es: 'Olimpiades Populars Barcelona',
    body: 'Protesta antifascista alternativa a los JJ.OO. de Berlín. Nunca llegó a inaugurarse: el golpe de Estado lo impidió el día antes. Muchos atletas extranjeros se unieron a las milicias populares.',
    img: './../fotos/15.jpeg',
  },
  {
    left: 3070, w: 90, h: 120,
    year: '1952',
    es: 'Esperando a Godot',
    body: 'Se sospecha que Beckett se inspiró en el corredor francés Roger Godeau, quien siempre llegaba el último.',
    img: './../fotos/57.jpg',
  },
  {
    left: 3240, w: 90, h: 180,
    year: '1960',
    es: 'Creación de los paralímpicos',
    body: 'El Dr. Guttmann organizó los primeros Juegos de Stoke Mandeville en 1948. Los primeros paralímpicos: Roma 1960.',
    img: './../fotos/16.jpeg',
  },
  {
    left: 3410, w: 310, h: 90,
    year: '1968',
    es: 'Las Gardenias de Tepito',
    body: 'Equipo de fútbol de travestis y transexuales que lleva 50 años jugando maquilladas y con lentejuelas en El Maracaná de Tepito.',
    img: './../fotos/17.jpg',
  },
  {
    left: 3800, w: 55, h: 200,
    year: '1968',
    es: 'Black Power en los JJ.OO. de México',
    body: 'Tommie Smith y John Carlos elevan el puño en el podio de los 200m el 16 de octubre de 1968. Protesta silenciosa contra la discriminación racial en Estados Unidos.',
    img: './../fotos/18.jpg',
  },
  {
    left: 3935, w: 55, h: 200,
    year: '1969',
    es: 'Stop the Seventy Tour',
    body: 'Sabotajes creativos a la gira de los Springboks en pleno Apartheid: zanjas nocturnas, miles de chinchetas, encadenamientos.',
    img: './../fotos/19.png',
  },
  {
    left: 4070, w: 110, h: 140,
    year: '1973',
    es: 'Grupo Passion — Deporte de Ideas',
    body: '«El dogma competitivo nos parece repugnante». Arte conceptual desde dentro del deporte.',
    img: './../fotos/20.jpg',
  },
  {
    left: 4260, w: 190, h: 50,
    year: '1974',
    es: 'Nace la lucha de dedos de los pies',
    body: 'Conocido como Toe Wrestling, este deporte fue inventado por unos ingleses en un bar.',
    img: './../fotos/21.jpg',
  },
  {
    left: 4530, w: 50, h: 290,
    year: '1982',
    es: 'Creación de los Gay Games',
    body: 'Creados en San Francisco por Tom Waddell, decatleta olímpico, para promover la inclusión de la comunidad gay y lesbiana.',
    img: './../fotos/22.webp',
  },
  {
    left: 4660, w: 80, h: 100,
    year: '1983',
    es: 'John Bonello recibe 12 goles',
    body: 'El portero de Malta encajó 12 goles contra España el 21 de diciembre de 1983. Años después protagonizó anuncios de cerveza Amstel parodiándose a sí mismo como «el amigo perfecto».',
    img: './../fotos/23.webp',
  },
  {
    left: 4820, w: 150, h: 100,
    year: '1984',
    es: 'Nado sincronizado individual',
    body: 'Deporte olímpico olvidado presente en tres olimpiadas: 1984, 1988 y 1992. Sincronizarse con une misme no siempre fue sencillo.',
    img: './../fotos/24.jpg',
  },
  {
    left: 5050, w: 120, h: 75,
    year: '1988',
    es: 'Florence Griffith',
    body: 'Tras batir el récord en Seúl se intensificó la campaña de acoso: dijeron que el velocímetro estaba roto, que hacía viento. Se sumaron cuestiones de género, raza y clase.',
    img: './../fotos/25.webp',
  },
  {
    left: 5250, w: 120, h: 75,
    year: '1988',
    es: 'Ballet de esquí en los JJ.OO. de invierno',
    body: 'Apenas duró dos Juegos Olímpicos de Invierno, 1988 y 1992, pero el ballet de esquí nos parece un deporte queer digno de admirar.',
    img: './../fotos/26.jpg',
  },
  {
    left: 5450, w: 80, h: 240,
    year: '1992',
    es: 'Petra, inspirada en Lorenza Böttner',
    body: 'Mascota paralímpica Barcelona 92, diseñada por Mariscal. Inspirada en Lorenza Böttner: pintora, performer, activista trans y anticapacitista.',
    img: './../fotos/27.jpg',
  },
  {
    left: 5610, w: 80, h: 80,
    year: '1993',
    es: 'James Miller cae en paracaídas sobre el ring',
    body: 'Irrumpe en el séptimo asalto del combate por el título mundial de pesos pesados. También interrumpió partidos de NFL, del Arsenal y Palacio de Buckingham.',
    img: './../fotos/28.png',
  },
  {
    left: 5770, w: 160, h: 65,
    year: '1993',
    es: 'Mark Roberts, el espontáneo más prolífico',
    body: 'Ha interrumpido más de 500 eventos deportivos incluyendo finales de Wimbledon, el Super Bowl y la Copa Mundial de Rugby, a menudo corriendo desnudo.',
    img: './../fotos/29.avif',
  },
  {
    left: 6010, w: 160, h: 65,
    year: '1996',
    es: 'Daniel Plaza da positivo por sexo oral',
    body: 'El marchador fue absuelto nueve años después de dar positivo en dopaje. Declaró que la nandrolona llegó a su cuerpo al practicar sexo oral con su mujer embarazada.',
    img: '',
  },
  {
    left: 6250, w: 160, h: 65,
    year: '1996',
    es: 'Redneck Games',
    body: 'En contestación a los JJ.OO. de Atlanta se crearon en Georgia los Redneck Games, con pruebas como salto de barriga al barro, lanzamiento de tapas de inodoro o serenata de axilas.',
    img: '',
  },
  {
    left: 6490, w: 160, h: 65,
    year: '2000',
    es: 'Eric Moussambani',
    body: 'Sídney 2000. Completó los 100m en 1:52.72, más del doble del tiempo ganador. Aprendió a nadar 8 meses antes en una piscina de hotel de 12 metros.',
    img: '',
  },
  {
    left: 6730, w: 160, h: 65,
    year: '2000',
    es: 'Escándalo paralímpico de Sídney',
    body: '10 de los 12 jugadores de la selección española de baloncesto para personas con discapacidad intelectual no tenían ninguna discapacidad. España fue despojada del oro.',
    img: './../fotos/30.avif',
  },
  {
    left: 6970, w: 100, h: 120,
    year: '2001',
    es: 'Circo Interior Bruto — La aventura de la esfera',
    body: 'Presentaron una obra para la Bienal del Deporte en el Arte en Valencia. Corrían con la luz apagada. Crearon un gimnasio con material doméstico: ollas, escaleras, cajas de cervezas.',
    img: './../fotos/31.jpg',
  },
  {
    left: 7150, w: 100, h: 100,
    year: '2001',
    es: 'Sueca United, el peor equipo indie del mundo',
    body: 'Fundado por Pau Codina para que jugaran quienes no tuvieron oportunidad en otros equipos. Un acercamiento al fracaso mezclado con música y ecologismo.',
    img: './../fotos/32.jpg',
  },
  {
    left: 7330, w: 100, h: 230,
    year: '2004',
    es: 'Nace Samarucs València',
    body: 'Primer club polideportivo LGTBIQ+ de la Comunitat Valenciana. De aquí nace Parkuir.',
    img: '',
  },
  {
    left: 7510, w: 140, h: 105,
    year: '2005',
    es: 'Nace el Quadball',
    body: 'Antes Quidditch. En 2022 cambió su nombre para desvincularse de J.K. Rowling tras sus declaraciones tránsfobas.',
    img: './../fotos/33.jpg',
  },
  {
    left: 7730, w: 160, h: 65,
    year: '2007',
    es: 'Acciones contra la Copa Amèrica a València',
    body: 'Colectivos de la ciudad respondieron con campaña de boicot denunciando el uso de dinero público para empresas privadas y la destrucción del territorio portuario.',
    img: './../fotos/34.jpg',
  },
  {
    left: 7970, w: 160, h: 65,
    year: '2008',
    es: 'El partido más largo de baloncesto',
    body: '3.917 puntos frente a 3.564. En La Laguna, Canarias. 24 jugadores estuvieron en pista durante 81 horas y un minuto.',
    img: './../fotos/35.jpg',
  },
  {
    left: 8210, w: 160, h: 65,
    year: '2008',
    es: 'Wim Vansevenant se retira del ciclismo',
    body: 'Consiguió quedar último en el Tour de Francia durante tres años consecutivos. Hizo del fracaso su éxito.',
    img: '',
  },
  {
    left: 8450, w: 75, h: 200,
    year: '2008',
    es: '100 metros valla con aletas de buceo',
    body: 'La mejor marca mundial la tiene el alemán Christopher Irmscher: 14,82 segundos en septiembre de 2008.',
    img: './../fotos/36.png',
  },
  {
    left: 8605, w: 200, h: 70,
    year: '2009',
    es: 'Caster Semenya vs World Athletics',
    body: 'Activista y atleta intersex. Rechaza medicarse para competir. Ha llevado su caso hasta el Tribunal Europeo de Derechos Humanos.',
    img: './../fotos/37.jpg',
  },
  {
    left: 8885, w: 160, h: 80,
    year: '2009',
    es: 'Se crea Nu Passión',
    body: 'En homenaje al Grupo Passion, integrado por artistas vinculados a la cultura. Revisaron las jugadas de 1977, las entrenaron, las modificaron e inventaron otras nuevas.',
    img: './../fotos/38.jpg',
  },
  {
    left: 9125, w: 75, h: 250,
    year: '2014',
    es: 'Space-out Competition',
    body: 'Competición que premia a quien no haga nada durante 90 minutos manteniendo el ritmo cardíaco estable. Fundada por Woopsyang en Corea del Sur.',
    img: './../fotos/39.png',
  },
  {
    left: 9280, w: 160, h: 80,
    year: '2015',
    es: 'Teresa Almeida, «la abanderada de la grasa»',
    body: 'La portera angoleña se autodenominó con orgullo «abanderada de la grasa» en el Mundial de 2015. Con casi 96 kilos, desafió los cánones estéticos del deporte.',
    img: './../fotos/40.png',
  },
  {
    left: 9520, w: 160, h: 80,
    year: '2016',
    es: 'Discofoot — Ballet de Lorraine',
    body: 'Coincidiendo con la Eurocopa, la compañía Ballet de Lorraine crea en Francia este deporte que mezcla fútbol y baile.',
    img: './../fotos/41.png',
  },
  {
    left: 9760, w: 160, h: 80,
    year: '2016',
    es: 'Alexa Moreno, víctima de gordofobia en Río',
    body: 'La gimnasta mexicana fue blanco de una campaña masiva de acoso centrada en su complexión física durante los Juegos Olímpicos de Río 2016.',
    img: '',
  },
  {
    left: 10000, w: 160, h: 80,
    year: '2018',
    es: 'Se estrena el documental King Ray',
    body: 'El documental hace justicia sobre la figura de Ramón Torres (Ray), tras el fraude de los Juegos Paralímpicos de Sídney 2000.',
    img: './../fotos/42.png',
  },
  {
    left: 10240, w: 160, h: 80,
    year: '2020',
    es: 'Se crea el Lesbian Garros',
    body: 'Torneo y liga de tenis/pádel amateur en Madrid para ofrecer un espacio seguro e inclusivo para la comunidad LGTBIQ+, especialmente mujeres, personas trans y no binarias.',
    img: './../fotos/43.jpg',
  },
  {
    left: 10480, w: 160, h: 80,
    year: '2020',
    es: 'Carri Richardson descalificada por marihuana',
    body: 'Descalificada de Tokio por dar positivo en marihuana, acusa a la AMA de trato racista: fue la única descalificada y la única negra entre quienes dieron positivo.',
    img: './../fotos/44.jpeg',
  },
  {
    left: 10720, w: 160, h: 80,
    year: '2021',
    es: 'Simone Biles · salud mental',
    body: 'Se retira de Tokio por salud mental, abriendo el debate sobre la presión psicológica en el deporte de élite.',
    img: './../fotos/45.png',
  },
  {
    left: 10960, w: 160, h: 80,
    year: '2022',
    es: 'Valentía Berr se retira denunciando presión psicológica',
    body: 'La jugadora del Europa se retiró del fútbol federado denunciando la vigilancia constante y la presión psicológica por ser una mujer trans.',
    img: './../fotos/46.jpeg',
  },
  {
    left: 11200, w: 130, h: 160,
    year: '2023',
    es: 'Activistas plantan cebollas en campos de golf',
    body: 'XR y otros grupos siembran hortalizas en diez campos de golf para denunciar el despilfarro de agua en plena sequía.',
    img: './../fotos/47.jpg',
  },
  {
    left: 11410, w: 250, h: 55,
    year: '2024',
    es: 'Sabotaje ferroviario en los JJ.OO. de París',
    body: 'Horas antes de la ceremonia de apertura, grupos anticapitalistas sabotearon coordinadamente la red ferroviaria de París protestando contra la higienización y expulsión de barrios obreros.',
    img: './../fotos/48.jpg',
  },
  {
    left: 11740, w: 250, h: 55,
    year: '2024',
    es: 'Imane Khelif · Paris 2024',
    body: 'Boxeadora argelina, oro en París. Recibió una campaña de odio transfóbica siendo mujer cis. Entre los atacantes: Elon Musk y J.K. Rowling.',
    img: './../fotos/49.jpg',
  },
  {
    left: 12070, w: 160, h: 80,
    year: '2024',
    es: 'Manual de buenas prácticas de la Guardia Civil',
    body: 'La Guardia Civil publica un manual de actuación en grandes eventos deportivos con un apartado sobre militantes anarquistas y sus posibles motivaciones.',
    img: './../fotos/50.png',
  },
  {
    left: 12310, w: 150, h: 80,
    year: '2024',
    es: 'Walking Football Barcelona',
    body: 'El fútbol que se juega a otro ritmo. Donde no se corre, no se para, solo se disfruta. Vas por el fútbol y te quedas por la amistad.',
    img: './../fotos/51.png',
  },
  {
    left: 12540, w: 150, h: 120,
    year: '2025',
    es: 'Se para la Vuelta a España por Israel',
    body: 'Diversas protestas contra la participación del equipo Israel-Premier Tech en pleno genocidio a Palestina culminaron en la cancelación de la última etapa en Madrid.',
    img: './../fotos/52.avif',
  },
  {
    left: 12770, w: 150, h: 120,
    year: '2026',
    es: 'Regresa Jimmy Jump del exilio',
    body: 'Uno de los mayores espontáneos del estado tuvo que exiliarse a Alemania para evitar pagar más de 350.000€. «Siempre para dar un mensaje de libertad».',
    img: './../fotos/53.avif',
  },
  {
    left: 13000, w: 150, h: 120,
    year: '2026',
    es: 'Protestas en Milán contra los JJ.OO. de Invierno',
    body: 'Grandes manifestaciones y sabotajes contra los Juegos Olímpicos de Invierno de Milán 2026, denunciando el impacto ambiental, la presencia del ICE y el uso de recursos públicos.',
    img: './../fotos/54.jpg',
  },
  {
    left: 13230, w: 130, h: 340,
    year: '2026',
    es: 'Primera Copa Mundial de Sperm Racing',
    body: 'La machosfera convierte la carrera de esperma en deporte mundial. Podría haber sido una broma irónica de Parkuir, pero ellos llegaron más lejos.',
    img: './../fotos/55.png',
  },
  {
    left: 13440, w: 150, h: 120,
    year: '2026',
    es: 'Gay Games Valencia',
    body: 'Evento LGTB+ cuya financiación incluye donaciones de General Electric, fabricante de componentes militares utilizados en conflictos activos, incluido el genocidio en Gaza.',
    img: './../fotos/56.png',
  },
];